apiVersion: manifests/v1beta1
metadata:
  name: simple-manifest
spec:
  chartTimeout: 10m0s # override default Helm install/upgrade timeout for any chart, a go duration: https://golang.org/pkg/time/#ParseDuration
  charts:
  - name: my-chart-1   # the name of the chart
    namespace: default # the namespace where your chart's resources should live
    version: 1.0.0     # the version of your chart to install
    # The values property allows passing in value overrides to your chart install/upgrade
    # e.g. https://helm.sh/docs/chart_template_guide/values_files/
    values:
      image:
        repository: gcr.io/my-project/my-image:1.9.0
  # and further charts to be installed or upgraded. Loftsman will go through this charts
  # list and install in order.
  - name: my-chart-2
    namespace: another-namespace # the namespace will be created if it doesn't already exist
    version: 1.7.5
    timeout: 12m30s # you can also override the Helm install/upgrade timeout on a per-chart basis
